import { getPortalContent } from "./portal-store";

export const dynamic = "force-dynamic";

export default async function Home() {
  const { courses, profile, publications } = await getPortalContent();
  return <main>
    <nav className="nav" aria-label="Ana navigasyon">
      <a className="brand" href="#baslangic">BAE<span>·</span>ECON</a>
      <div className="nav-links"><a href="#profil">Profil</a><a href="#yayinlar">Yayınlar</a><a href="#dersler">Dersler</a><a href="#iletisim">Bağlantılar</a></div>
      <a className="nav-cta" href="#dersler">Dersler <span>↗</span></a>
    </nav>
    <section className="hero" id="baslangic"><div className="hero-copy"><p className="eyebrow">{profile.title.toUpperCase()}</p><h1>Burak Alparslan<br/><em>Eroğlu</em></h1><p className="hero-text">Zaman serisi analizi, finansal ekonometri ve makroekonomi alanlarında araştırma ve öğretim.</p><div className="hero-actions"><a className="button dark" href="#profil">Profil <span>↓</span></a><a className="text-link" href="#dersler">Derslere git →</a></div></div><div className="hero-side"><div className="orbit"><div className="orbit-core">BAE</div><span className="dot d1"/><span className="dot d2"/><span className="dot d3"/><span className="dot d4"/></div><p className="side-note">İzmir · Türkiye<br/>{profile.institution}</p></div></section>
    <section className="profile section" id="profil"><div className="section-label"><span>01</span><p>PROFİL</p></div><div className="profile-content"><h2>Akademik<br/><em>profil</em></h2><div className="profile-text"><p>{profile.bio}</p><p>{profile.detail}</p><a className="text-link" href={profile.cvUrl} target="_blank" rel="noreferrer">Akademik özgeçmişi görüntüle →</a></div></div><div className="focus-grid"><article><b>01</b><h3>Zaman Serileri</h3><p>Mevsimsel dinamikler, birim kökler, eşbütünleşme ve çıkarım.</p></article><article><b>02</b><h3>Finansal Ekonometri</h3><p>Volatilite, risk ölçümü, dalgacıklar ve finansal modelleme.</p></article><article><b>03</b><h3>Makro-Finans</h3><p>Ekonomik ve finansal sorunlarda güvenilir politika çıkarımı.</p></article></div></section>
    <section className="research section" id="yayinlar"><div className="section-label"><span>02</span><p>SEÇİLMİŞ YAYINLAR</p></div><div className="publication-list">{publications.map((item, index) => <article className="publication" key={item.title}><span className="pub-index">{String(index + 1).padStart(2,"0")}</span><div><p className="pub-year">{item.year}</p><h3>{item.title}</h3><p className="journal">{item.journal}</p></div>{"url" in item ? <a href={item.url} target="_blank" rel="noreferrer" aria-label={`${item.title} bağlantısı`}>↗</a> : <span className="publication-spacer"/>}</article>)}</div><a className="button outline" href={profile.researchUrl} target="_blank" rel="noreferrer">Yayınlar, çalışmalar ve kodlar <span>→</span></a></section>
    <section className="teaching section" id="dersler"><div className="section-label"><span>03</span><p>DERSLER</p></div><div className="teaching-intro"><h2>Ders<br/><em>bilgileri</em></h2><p>Ders notları, uygulamalar ve güncel duyurular.</p></div><div className="course-list">{courses.map(([code,title,language]) => { const isEys = code.toUpperCase().startsWith("EYS 2026"); return <a className="course" href={isEys ? "/dersler/eys-2026" : profile.teachingUrl} target={isEys ? undefined : "_blank"} rel={isEys ? undefined : "noreferrer"} key={code}><span className="course-code">{code}</span><h3>{title}</h3><span className="level">{language}</span><span className="course-arrow">→</span></a>; })}</div></section>
    <section className="contact" id="iletisim"><p className="eyebrow">BAĞLANTILAR</p><h2>Akademik<br/><em>bağlantılar</em></h2><a href={profile.cvUrl} target="_blank" rel="noreferrer" className="email">Akademik özgeçmiş <span>↗</span></a><div className="footer-line"><span>© 2026 {profile.name}</span><span>{profile.institution}</span><span>Türkçe / EN</span></div></section>
  </main>;
}
